config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  #  Users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get "users/:id/my_posts", to: "users#my_posts", as: 'my_posts' 
  get "users/:id/my_jobs", to: "users#my_jobs", as: 'my_jobs' 

  #  Admin
  get 'admin', to: 'admin#home'   
  get 'admin/job_requests', to: 'admin#job_requests'
  get 'admin/job_show/:id', to: 'admin#job_show', as: 'admin_job_show'
  post 'admin/job_approve/:id', to: 'admin#job_approve', as: 'admin_job_approve'
  delete 'admin/job_reject/:id', to: 'admin#job_reject', as: 'admin_job_reject' 

  # Sessions
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Sector & Types
  scope :admin do
    resources :sectors
    resources :types
  end

  # Jobs
  resources :jobs do
    resources :reviews
  end
  resources :posts
  post 'respond_to_candidate/:id', to: 'posts#respond_to_candidate', as: 'respond_to_candidate'
  delete 'reject_candidate/:id', to: 'posts#reject_candidate', as: 'reject_candidate'
  
  # Chatroom
  get "chatroom", to: "chatroom#index"  
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'

  # Google Ouath
  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/views/admin/home.html.erb
<h1 class>Welcome to Admin Panel</h1>
<%=link_to "View Sectors", sectors_path, class: "btn btn-primary btn-lg mt-3 mx-2"%>
<%=link_to "View Types", types_path, class: "btn btn-primary btn-lg mt-3 mx-2"%>
<%=link_to "Job Requests", admin_job_requests_path, class: "btn btn-primary btn-lg mt-3 mx-2"%>

app/views/admin/job_requests.html.erb
<div class="text-center">
    <h1>All job requests are listed</h1>
    <%res = @jobs.select {|job| job.approved_by == 0}%>
        <%if res.length == 0 %>
            <h3 class = "text-success mt-4">No Job request is pending</h3>
        <%end%>
</div>
<div class="container mt-4">
    <%@jobs.each do |j|%>
        <% if j.approved_by == 0 %>    
            <div class="row justify-content-md-center">
                <div class="col-6 mt-6">
                    <div class="card border-secondary shadow mb-5 bg-white rounded post-card">
                    <div class="card-header text-center font-weight-bold text-success " id = "post-head">    
                        Posted By <%= link_to j.user.username, user_path(j.user)%>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-danger text-left text-decoration-none"> <%= link_to j.title, admin_job_show_path(j) %></h5>
                        <p class="card-text"><%= truncate(j.job_description, length: 100) %></p>
                        <p > <span><strong>Location:</strong></span> <%= j.job_location%></p>
                        <p> <span><strong>Skills Required:</strong></span> <%=j.keyskills%></p>
                        <div class="text-center">
                            <%= link_to "View", admin_job_show_path(j), class: "btn btn-outline-primary"%> 
                        </div>
                        <% if %>
                        
                        <%end%>
                    </div>
                    <div class="card-footer text-muted text-center">
                        <small> Created <%= time_ago_in_words(j.created_at)%> ago, Edited <%= time_ago_in_words(j.updated_at)%> ago</small>
                    </div>
                    </div>
                </div>
            </div>
        <%end%>
    <%end%>
</div>

app/views/admin/job_show.html.erb
<h1 class = "text-center">Job Show For Admin</h1>
<div class="container job-container">
    <div class="row justify-content-center">
        <div class="col-8 mt-6">
            <div class="card border-secondary shadow mb-5 text-center bg-white rounded job-card">
                <div class="card-header border-secondary text-center font-weight-bold " id = "job-head">    
                    <strong><%= @job.organisation_name%></strong>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-success text-left text-decoration-none"><%=@job.title%></h5>
                    <p class="card-text"><%= simple_format(@job.job_description) %></p>
                    <p > <span><strong>Location:</strong></span> <%= @job.job_location%></p>
                    <p> <span><strong> Skills Required:</strong></span> <%=@job.keyskills%></p>
                    <p> <span><strong> Sector:</strong></span> <%=@job.sector.name%></p>
                    <p> <span><strong> Type:</strong></span> <%=@job.type.name%></p>
                    <p> <span><strong> Recruiter:</strong></span> <%=link_to @job.user.username, user_path(@job.user), class: "text-danger"%></p>
                    <%= button_to "Accept", admin_job_approve_path, class: "btn btn-success mb-4"%>
                    <%= link_to "Reject", admin_job_reject_path(@job), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to delete this job?"
                      }, class:"btn btn-danger" %>
                </div>
                <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(@job.created_at)%> ago, Edited <%= time_ago_in_words(@job.updated_at)%> ago</small>
                </div>
            </div>
        </div>
    </div>
</div>
    