config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  #  Users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get "users/:id/my_posts", to: "users#my_posts", as: 'my_posts' 
  get "users/:id/my_jobs", to: "users#my_jobs", as: 'my_jobs' 

  #  Admin
  get 'admin', to: 'admin#home'   
  get 'admin/job_requests', to: 'admin#job_requests'
  get 'admin/job_show/:id', to: 'admin#job_show', as: 'admin_job_show'
  post 'admin/job_approve/:id', to: 'admin#job_approve', as: 'admin_job_approve'
  delete 'admin/job_reject/:id', to: 'admin#job_reject', as: 'admin_job_reject' 

  # Sessions
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Sector & Types
  scope :admin do
    resources :sectors
    resources :types
  end

  # Jobs
  resources :jobs do
    resources :reviews
  end
  resources :posts
  post 'respond_to_candidate/:id', to: 'posts#respond_to_candidate', as: 'respond_to_candidate'
  delete 'reject_candidate/:id', to: 'posts#reject_candidate', as: 'reject_candidate'
  
  # Chatroom
  get "chatroom", to: "chatroom#index"  
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'

  # Google Ouath
  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/job.rb
class Job < ApplicationRecord
    paginates_per 3
    belongs_to :user
    belongs_to :type
    belongs_to :sector
    has_many :posts, dependent: :destroy
    has_many :reviews, dependent: :destroy

    # Validations
    VALID_TITLE = /\A([a-zA-Z]){2}([a-zA-Z\-\s]){1,25}([0-9]){0,2}\z/
    validates :title, presence: true, format: {with: VALID_TITLE}
    validates :job_description, presence: true
    VALID_NAMES = /\A([a-zA-Z]){2}[^`!@#\$%\^&*+_=]+\z/
    validates :job_location, presence: true, length: {minimum: 3, maximum: 40}, format: {with: VALID_NAMES}
    validates :keyskills, presence: true, length: {minimum: 2}, format: {with: VALID_NAMES}
    validates :organisation_name, presence: true, length: { minimum: 3, maximum: 40}, format: {with: VALID_NAMES}

    # Scope
    scope :sector, ->(abc) { joins(:sector).where("name LIKE?", "%#{abc}%")}
    scope :type, ->(abc) { joins(:type).where("name LIKE?", "%#{abc}%")}
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :require_user , only: [:show] 
    before_action :require_recruiter , except: [:index, :show] 
    before_action :require_same_recruiter, only: [:edit, :update, :destroy] 

    def index
        if params[:query].present?
            @jobs = Job.where("title LIKE ? OR job_location LIKE ? OR keyskills LIKE?", "%#{params[:query]}%","%#{params[:query]}%", "%#{params[:query]}%").page params[:page]
        elsif params[:sector].present?
            @jobs = Job.all.sector(params[:sector]).page params[:page]
        elsif params[:type].present?
            @jobs = Job.all.type(params[:type]).page params[:page]    
        else
            @jobs = Job.page params[:page]
        end
    end
    
    def show
        @job = Job.find(params[:id])
    end

    def new
        @job = Job.new
    end

    def create
        @job = Job.new(job_params)
        @job.user = current_user
        if @job.save
          flash[:success] = "Job successfully created and pending for admin approval"
          redirect_to jobs_path
        else
          flash[:notice] = "Job cannot be created due to some errors"
          render 'new', status: :unprocessable_entity
        end
    end

    def edit
        @job = Job.find(params[:id])
    end

    def update
        @job = Job.find(params[:id])
        if @job.update(job_params)
          flash[:success] = "Job was successfully updated"
          redirect_to jobs_path
        else
          flash[:notice] = "Job cannot be updated due to some errors"
          render 'edit', status: :unprocessable_entity
        end
    end
    
    def destroy
        @job = Job.find(params[:id])
        if @job.destroy
            flash[:success] = 'Job is successfully deleted.'
            redirect_to jobs_path, status: :see_other
        else
            flash[:notice] = 'There was an error regarding deletion of this job'
            redirect_to jobs_path, status: :see_other
        end
    end
    
    private
    def job_params
        params.require(:job).permit(:title, :job_description, :job_location, :keyskills, :sector_id, :type_id, :user_id, :organisation_name)
    end

    def require_same_recruiter
        @job = Job.find(params[:id])
        if current_user != @job.user
            flash[:danger] = "You can only edit or delete your own jobs"
            redirect_to jobs_path
        end
    end
    
end

app/views/jobs/_job.html.erb
<div class="container job-container">
    <%if @job.approved_by != 0%>
      <div class="row justify-content-center">
          <div class="col-8 mt-6">
            <div class="card shadow mb-5 text-center bg-white rounded job-card">
              <div class="card-header text-center font-weight-bold " id = "job-head">    
                  By <%= @job.organisation_name%>
              </div>
              <div class="card-body">
                <h5 class="card-title text-success text-left text-decoration-none"><%=@job.title%></h5>
                <p class="card-text"><%= simple_format(@job.job_description) %></p>
                <p > <span> <strong> Location:</strong></span> <%= @job.job_location%></p>
                <p> <span> <strong> Skills Required:</strong></span> <%=@job.keyskills%></p>
                <p> <span> <strong> Sector:</strong></span> <%=@job.sector.name%></p>
                <p> <span> <strong> Type:</strong></span> <%=@job.type.name%></p>
                <%if current_user.is_candidate?%>
                  <%=link_to "Apply for this Job", new_post_path(job_id: @job.id), class: "btn btn-primary"%>
                <%end%>
                <% if @job.user == current_user%>
                  <%=link_to "Post Requests", posts_path(job_id: @job.id), class: "btn btn-outline-primary"%>
                  <%= link_to "Edit", edit_job_path(@job), class: "btn btn-outline-success"%>
                  <%= link_to "Delete", job_path(@job), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete this job?"
                  }, class: "btn btn-outline-danger"%>
                <%end%>
              </div>
              <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(@job.created_at)%> ago, Edited <%= time_ago_in_words(@job.updated_at)%> ago</small>
              </div>
            </div>
          </div>
      </div>
  <%end%>
</div>

app/views/jobs/_jobs.html.erb
<div class="container job-container">
  <% @jobs.each do |job| %>
    <%if job.approved_by != 0%>
      <div class="row justify-content-center">
          <div class="col-6 mt-6">
            <div class="card shadow mb-5 bg-white rounded job-card">
              <div class="card-header text-center font-weight-bold " id = "job-head">    
                  By <%= job.organisation_name%>
              </div>
              <div class="card-body jobs-body">
                <h5 class="card-title text-success text-left text-decoration-none"><%= link_to job.title, job_path(job)%></h5>
                <p class="card-text"><%= truncate(job.job_description, length: 100) %></p>
                <p ><span>Location:</span> <%= job.job_location%></p>
                <p><span> Skills Required:</span> <%=job.keyskills%></p>
                <div class="text-center">
                  <%= link_to "View", job_path(job), class: "btn btn-outline-primary mx-1"%> 
                  <% if logged_in? && job.user == current_user%>
                    <%= link_to "Edit", edit_job_path(job), class: "btn btn-outline-success mx-1" %>
                    <%= link_to "Delete", job_path(job), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "btn btn-outline-danger mx-1"%>
                  <%end%>
                </div>
              </div>
              <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(job.created_at)%> ago, Edited <%= time_ago_in_words(job.updated_at)%> ago</small>
              </div>
            </div>
          </div>
      </div>
    <%end%>
  <%end%>
</div>

app/views/jobs/edit.html.erb
<div class="container mb-4">
    <h1>Edit this job</h1>
    <%= render 'shared/errors', obj: @job %>
    <%= form_with(model: @job) do |f|%>
             <div class="form-group row mb-4">
            <%= f.label :title, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :title, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :job_description, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_area :job_description, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :job_location, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :job_location, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :keyskills, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :keyskills, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :organisation_name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :organisation_name, class: "form-control" %> 
            </div>
        </div>
        <div class= "mb-4"> 
            <%= f.label :sector, class: "col-sm-2 col-form-label"%>
            <%= f.collection_select(:sector_id, Sector.all, :id, :name,
                { prompt: "Select a Job Sector"}, class: "col-4 form p-2") %>
            <div class="job-form-align mx-2">
                <span class = "mx-2"> Or </span>
                <%=link_to "Create a New Sector", new_sector_path, class: "btn btn-info"%>
            </div>
        </div>
        <div class = "mb-4">
            <%= f.label :type, class: "col-sm-2 col-form-label"%>
            <%= f.collection_select(:type_id, Type.all, :id, :name,
                { prompt: "Select a Job Type"}, class: "col-4 form p-2") %>
            <div class="job-form-align mx-2">
                <span class = "mx-2"> Or </span>
                <%=link_to "Create a New Type", new_type_path, class: "btn btn-info"%>
            </div>
        </div>
        <br>
        <%=f.submit "Submit", class: "btn btn-success"%>
    <%end%>
</div>

app/views/jobs/index.html.erb
<h1 class = "text-center">List all Jobs</h1>
<div class="flickr_pagination d-flex justify-content-center mt-4">
    <%= paginate @jobs%>
</div>
<%=render 'jobs' %>
<div class="flickr_pagination d-flex justify-content-center mb-4">
    <%= paginate @jobs%>
</div>

app/views/jobs/new.html.erb
<div class="container mb-4">
    <h1>Create a new Job</h1>
    <%= render 'shared/errors', obj: @job %>
    <%= form_with(model: @job) do |f|%>
        <div class="form-group row mb-4">
            <%= f.label :title, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :title, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :job_description, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_area :job_description, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :job_location, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :job_location, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :keyskills, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :keyskills, class: "form-control" %> 
            </div>
        </div>
        <div class="form-group row mb-4">
            <%= f.label :organisation_name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-4">
                <%= f.text_field :organisation_name, class: "form-control" %> 
            </div>
        </div>
        <div class= "mb-4"> 
            <%= f.label :sector, class: "col-sm-2 col-form-label"%>
            <%= f.collection_select(:sector_id, Sector.all, :id, :name,
                { prompt: "Select a Job Sector"}, class: "col-4 form p-2") %>
            <div class="job-form-align mx-2">
                <span class = "mx-2"> Or </span>
                <%=link_to "Create a New Sector", new_sector_path, class: "btn btn-info"%>
            </div>
        </div>
        <div class = "mb-4">
            <%= f.label :type, class: "col-sm-2 col-form-label"%>
            <%= f.collection_select(:type_id, Type.all, :id, :name,
                { prompt: "Select a Job Type"}, class: "col-4 form p-2") %>
            <div class="job-form-align mx-2">
                <span class = "mx-2"> Or </span>
                <%=link_to "Create a New Type", new_type_path, class: "btn btn-info"%>
            </div>
        </div>
        <br>
        <%=f.submit "Submit", class: "btn btn-success"%>
    <%end%>
</div>

app/views/jobs/show.html.erb
<h1 class = "text-center">Job Show</h1>
<div class="text-center container">
  <div class="row">
    <%= render 'job'%>
  </div>
  <div class="row mb-4">
      <%= render 'reviews/review'%>
  </div>
</div>