config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  #  Users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get "users/:id/my_posts", to: "users#my_posts", as: 'my_posts' 
  get "users/:id/my_jobs", to: "users#my_jobs", as: 'my_jobs' 

  #  Admin
  get 'admin', to: 'admin#home'   
  get 'admin/job_requests', to: 'admin#job_requests'
  get 'admin/job_show/:id', to: 'admin#job_show', as: 'admin_job_show'
  post 'admin/job_approve/:id', to: 'admin#job_approve', as: 'admin_job_approve'
  delete 'admin/job_reject/:id', to: 'admin#job_reject', as: 'admin_job_reject' 

  # Sessions
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Sector & Types
  scope :admin do
    resources :sectors
    resources :types
  end

  # Jobs
  resources :jobs do
    resources :reviews
  end
  resources :posts
  post 'respond_to_candidate/:id', to: 'posts#respond_to_candidate', as: 'respond_to_candidate'
  delete 'reject_candidate/:id', to: 'posts#reject_candidate', as: 'reject_candidate'
  
  # Chatroom
  get "chatroom", to: "chatroom#index"  
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'

  # Google Ouath
  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    paginates_per 9
    enum role: [:candidate, :recruiter, :admin]
    VALID_USERNAME = /\A([a-zA-Z]){2}([0-9a-zA-Z_.@\-\s]){1,25}\z/
    validates :username, presence: true, uniqueness: { case_sensitive: false },
                format:{with: VALID_USERNAME}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false },
                format:{ with: VALID_EMAIL_REGEX}
    
    has_secure_password
    

    # Posts
    has_many :posts, dependent: :destroy

    # Sectors & Types
    has_many :sectors
    has_many :types

    #Jobs
    has_many :jobs, dependent: :destroy

    # Messages
    has_many :messages, dependent: :destroy
    
    # Reviews
    has_many :reviews

    def is_admin?
        role == "admin"
    end

    def is_recruiter?
        role == "recruiter"
    end

    def is_candidate?
        role == "candidate"
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_user, only: [:show]
    before_action :require_same_user, only: [:edit, :update, :destroy, :my_posts, :my_jobs]
    before_action :require_candidate, only: [:my_posts]
    before_action :require_recruiter, only: [:my_jobs]
    before_action :require_admin, only: [:index]

    def new
        @user = User.new
    end

    def show
  
    end
    
    def edit
        
    end

    def create
        @user = User.new(user_params)
        if @user.save && @user.is_candidate?
            session[:user_id] = @user.id
            flash[:success] = "candidate was created successfully."
            redirect_to @user
        elsif @user.save && @user.is_recruiter?
            session[:user_id] = @user.id
            flash[:success] = "recruiter was created successfully."
            redirect_to @user
        elsif @user.save && @user.is_admin?
            session[:user_id] = @user.id
            flash[:success] = "admin was created successfully."
            redirect_to admin_path
        else
            flash[:notice] = "There was a problem creating the user"
            render 'new', status: :unprocessable_entity
        end
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated!"
            redirect_to @user
        else
            flash.now[:notice] = "There was an error updating your account information."
            render 'edit', status: :unprocessable_entity
        end
    end

    def index
        @users = User.page params[:page]
    end

    def destroy
        if @user.destroy
            session[:user_id] = nil
            flash[:danger] = "Account successfully deleted"    
            redirect_to root_path, status: :see_other
        else
            flash[:notice] = "There was a problem deleting this account. Please Try again"
            redirect_to root_path, status: :see_other
        end
    end

    def my_posts
        @user = User.find(params[:id])
        @my_posts = @user.posts.page params[:page]
    end

    def my_jobs
        @user = User.find(params[:id])
        @my_jobs = @user.jobs.page params[:page]
    end

    private
        def user_params
            params.require(:user).permit(:username,:email,:password,:role)
        end

        def set_user
            @user = User.find(params[:id])
        end

        def require_same_user
            @user = User.find(params[:id])
            if current_user != @user
              flash[:danger] = "You can only edit or delete your own account"
              session[:user_id] = nil
              redirect_to login_path
            end
        end
end

app/views/users/edit.html.erb
<h1>Edit Your Profile Details</h1>
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user,class: "shadow p-3 mb-5 bg-success rounded mt-4") do |f| %>
    <div class = "form-group row">
        <%= f.label :username, class: "col-2 col-form-label text-light "%><br/>
        <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder:"Enter an Username"%>
        </div>
    </div>
    <div class = "form-group row mt-4">
        <%= f.label :email, class: "col-2 col-form-label text-white" %><br/>
        <div class="col-10">
            <%= f.email_field :email, rows:10, class: "form-control shadow rounded", placeholder:"Enter your email"%>
        </div>
    </div>
    <div class = "form-group row mt-4">
        <%= f.label :password, class: "col-2 col-form-label text-white" %><br/>
        <div class="col-10">
            <%= f.password_field :password, rows:10, class: "form-control shadow rounded", placeholder:"Enter your password"%>
        </div>
    </div>   
    <div class = "text-center" style = "margin-top:15px;">
        <%= f.submit class: "btn btn-primary"%>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>List of users</h1>
<% @users.each do |user|%>
    <div class="card border-warning sector-card mx-4 my-4" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title text-dark"><%= link_to user.username, user%></h5>
            <div class="text-center">
                <%= link_to "View", user, class: "btn btn-outline-primary"%>
            </div>
        </div>
    </div>
<%end%>
<div class="flickr_pagination d-flex justify-content-center mt-4">
    <%= paginate @users%>
</div>

app/views/users/my_jobs.html.erb
<h1 class="text-center">See Your Approved Jobs</h1>
<div class="container job-container">
  <% @my_jobs.each do |job| %>
    <%if job.approved_by != 0%>
      <div class="row justify-content-center">
          <div class="col-6 mt-6">
            <div class="card shadow mb-5 bg-white rounded job-card">
              <div class="card-header text-center font-weight-bold " id = "job-head">    
                  By <%= job.organisation_name%>
              </div>
              <div class="card-body jobs-body">
                <h5 class="card-title text-success text-left text-decoration-none"><%= link_to job.title, job_path(job)%></h5>
                <p class="card-text"><%= truncate(job.job_description, length: 100) %></p>
                <p > <span>Location:</span> <%= job.job_location%></p>
                <p> <span> Skills Required:</span> <%=job.keyskills%></p>
                <div class="text-center">
                  <%= link_to "View", job_path(job), class: "btn btn-outline-primary mx-1"%> 
                  <% if logged_in? && job.user == current_user%>
                    <%= link_to "Edit", edit_job_path(job), class: "btn btn-outline-success mx-1"%>
                    <%= link_to "Delete", job_path(job), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "btn btn-outline-danger mx-1"%>
                  <%end%>
                </div>
              </div>
              <div class="card-footer text-muted text-center">
                <small> Created <%= time_ago_in_words(job.created_at)%> ago, Edited <%= time_ago_in_words(job.updated_at)%> ago</small>
              </div>
            </div>
          </div>
      </div>
    <%end%>
  <%end%>
</div>

app/views/users/my_posts.html.erb
<h1 class = "text-center">See your Job Posts</h1>
<% @my_posts.each do |post|%>
    <div class="container  post-container mt-4">
        <div class="row justify-content-center">
            <div class="col-6 mt-6">
                <div class="card border-secondary shadow mb-5 bg-white roundedpost-card">
                <div class="card-header border-secondary text-center font-weight-bold " id = "post-head">    
                    Posted By <%= link_to post.user.username, user_path(post.user)%>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-success text-left text-decoration-none"> <%= post.name%></h5>
                    <p class="card-text"><%= post.post_description %></p>
                    <p> <strong> Phone Number:</strong> <%= post.phone_number%></p>
                    <p> <strong> City:</strong> <%=post.city%></p>
                    <p> <strong> Username:</strong> <%=post.username%></p>
                    <%if post.is_approved?%>
                        <p><strong>Job Status:</strong> Approved</p>
                    <%else%>
                        <p><strong>Job Status:</strong> Pending</p>
                    <%end%>
                    <div class="text-center">
                        <% if post.file.attached?%>
                            <%=button_to post.file.filename, url_for(post.file), method: :get, class: "btn btn-primary"%>
                        <%end%>
                    </div>
                </div>
                <div class="card-footer text-muted text-center">
                    <small> Created <%= time_ago_in_words(post.created_at)%> ago</small>
                </div>
                </div>
            </div>
        </div>
    </div>
<%end%>
<div class="flickr_pagination d-flex justify-content-center mt-4">
    <%= paginate @my_posts%>
</div>

app/views/users/new.html.erb
<h1 class = "text-center mb-4" >SignUp Here!</h1>
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user,class: "shadow p-3 mb-5 bg-success rounded") do |f| %>
    <div class = "form-group row">
        <%= f.label :username, class: "col-2 col-form-label text-light "%><br/>
        <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder:"Enter an Username"%>
        </div>
    </div>
    <div class = "form-group row mt-4">
        <%= f.label :email, class: "col-2 col-form-label text-white" %><br/>
        <div class="col-10">
            <%= f.email_field :email, rows:10, class: "form-control shadow rounded", placeholder:"Enter your email"%>
        </div>
    </div>
    <div class = "form-group row mt-4">
        <%= f.label :password, class: "col-2 col-form-label text-white" %><br/>
        <div class="col-10">
            <%= f.password_field :password, rows:10, class: "form-control shadow rounded", placeholder:"Enter your password"%>
        </div>
    </div>
    <div class = "form-group row mt-4">
        <%= f.label :role, class: "col-2 col-form-label text-white" %><br/>
        <div class="col-10">
            <%= f.select :role,["candidate", "recruiter"], class: "col-4 form p-2" %>
        </div>
    </div>
    <div class = "text-center" style = "margin-top:15px;">
        <%= f.submit class: "btn btn-primary"%>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>
<div class="col-md-8 mt-4">
  <div class="card mb-3">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0"><strong> Name: </strong></h6>
        </div>
        <div class="col-sm-9 text-secondary">
         <h6><%= @user.username %></h6>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0"><strong>Email:</strong></h6>
        </div>
        <div class="col-sm-9 text-secondary">
          <h6><%=@user.email%></h6>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0"><strong>Role:</strong></h6>
        </div>
        <div class="col-sm-9 text-secondary">
          <h6><%= @user.role%></h6>
        </div>
      </div>
    </div>
  </div>
</div>

<%if current_user == @user%>

  <%= link_to ' <i class="fa fa-gear"></i> Edit Profile '.html_safe, edit_user_path, class: "btn btn-secondary btn-lg mx-2" %>

  <%= link_to ' <i class="fas fa-briefcase"></i> Find Jobs '.html_safe, jobs_path, class: "btn btn-info btn-lg mx-2" %>

  <%if current_user.is_admin?%>
    <%= link_to ' <i class="fas fa-user-friends"></i> See Users '.html_safe, users_path, class: "btn btn-success btn-lg mx-2" %>
  <%end%>

  <%= link_to ' <i class="fas fa-trash"></i> Delete Your Account '.html_safe, user_path(@user), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete your account?"},class: "btn btn-danger btn-lg mx-2" %>
  

  <div class = "mt-4">
    <%if current_user.is_candidate?%>
      <%= link_to ' <i class="fas fa-folder"></i> My Posts '.html_safe, my_posts_path, class: "btn btn-danger btn-lg mx-2" %>
      <%= link_to ' <i class="far fa-comments"></i> Chat Here '.html_safe, chatroom_path, class: "btn btn-primary btn-lg mx-2" %>
    <%end%>
    <%if current_user.is_recruiter?%>
      <%= link_to ' <i class="fas fa-folder"></i> My Jobs '.html_safe, my_jobs_path, class: "btn btn-primary btn-lg mx-2" %>
      <%= link_to ' <i class="fas fa-pen"></i> Create Job '.html_safe, new_job_path, class: "btn btn-primary btn-lg mx-2" %>
    <%end%>
  </div>
<%end%>

<%if @user.role == nil%>
  <h1>Select a Role</h1>
    <%= form_with(model: @user,class: "shadow p-3 mb-5 bg-success rounded") do |f| %>
      <div class = "form-group row mt-4">
        <%= f.label :role, class: "col-2 col-form-label text-white" %><br/>
        <div class="col-10">
          <%= f.select :role, ["candidate", "recruiter"], class: "mx-1"%>
          <%= f.submit "Choose a Role", class: "btn btn-primary mx-5"%>
        </div>
      </div>
    <%end%>
<%end%>