config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  #  Users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get "users/:id/my_posts", to: "users#my_posts", as: 'my_posts' 
  get "users/:id/my_jobs", to: "users#my_jobs", as: 'my_jobs' 

  #  Admin
  get 'admin', to: 'admin#home'   
  get 'admin/job_requests', to: 'admin#job_requests'
  get 'admin/job_show/:id', to: 'admin#job_show', as: 'admin_job_show'
  post 'admin/job_approve/:id', to: 'admin#job_approve', as: 'admin_job_approve'
  delete 'admin/job_reject/:id', to: 'admin#job_reject', as: 'admin_job_reject' 

  # Sessions
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Sector & Types
  scope :admin do
    resources :sectors
    resources :types
  end

  # Jobs
  resources :jobs do
    resources :reviews
  end
  resources :posts
  post 'respond_to_candidate/:id', to: 'posts#respond_to_candidate', as: 'respond_to_candidate'
  delete 'reject_candidate/:id', to: 'posts#reject_candidate', as: 'reject_candidate'
  
  # Chatroom
  get "chatroom", to: "chatroom#index"  
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'

  # Google Ouath
  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/post.rb
class Post < ApplicationRecord
    paginates_per 2
    belongs_to :user
    has_one_attached :file
    belongs_to :job

    # Validations
    validates :name, presence: true, format: {with: /\A[^0-9`!@#\$%\^&*+_=]+\z/}, length: {minimum:3}
    validates :post_description, presence: true
    validates :username, presence: true, uniqueness: { case_sensitive: false },
                format:{with: /\A([a-zA-Z]){2}([0-9a-zA-Z_.@\-\s]){1,25}\z/}
    validates :phone_number, presence: true, numericality: true, length: {minimum: 10, maximum: 10}
    validates :city, presence: true, format:{with: /\A([a-zA-Z]){2}[^`!@#\$%\^&*+_=]+\z/}
    validates :file, content_type: ['application/pdf'], attached: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_candidate , only: [:new, :create] 
    before_action :require_recruiter, only: [:index, :destroy, :show]
    before_action :require_same_post_id, only: [:show, :destroy]

    def new
        @post = Post.new
        @job = Job.find(params[:job_id])        
    end

    def create      
        @post = Post.create(post_params)    
        @job = Job.find(params[:job_id])
        @post.job = @job        
        @post.user = current_user 
       if @post.save
          flash[:success] = "Job Post successfully created"
          redirect_to @job
        else
          flash[:danger] = "Incorrect Credentials"
          render "new", status: :unprocessable_entity
        end
    end
    
    def show
        @post = Post.find(params[:id])
    end

    def index
        @posts = Post.all    
        @job = Job.find(params[:job_id])
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.destroy
            flash[:success] = "Job post successfully deleted"
            redirect_to job_path(@post.job), status: :see_other
        else
            flash[:danger] = "There was a problem regarding deletion of this post"
            redirect_to job_path(@post.job), status: :see_other
        end
    end

    def respond_to_candidate
        @post = Post.find(params[:id])   
        if @post.save
            @post.is_approved = true
            @post.save! 
            flash[:notice] = "Mail has been sent to the candidate"
            RespondMailer.respond_to_candidate(@post).deliver_later
            redirect_to post_path(@post)
        else
            flash[:notice] = "Due to some errors mail cannot be sent"
            redirect_to post_path(@post)
        end
    end

    def reject_candidate
        @post = Post.find(params[:id])
        RespondMailer.reject_candidate(@post).deliver_now
        if @post.destroy
            flash[:notice] = "The post has been deleted"
            redirect_to job_path(@post.job), status: :see_other
        else
            flash[:notice] = "There was some error regarding deletion of this post"
            redirect_to job_path(@post.job), status: :see_other
        end
    end

    private
    def post_params
        params.require(:post).permit(:name, :post_description, :username, :phone_number, :city, :file,:job_id)
    end

    def require_same_post_id
        if current_user.is_recruiter?
            @post = Post.find(params[:id])
            job_ids = current_user.jobs.ids
            if !job_ids.include? @post.job.id
                flash[:danger] = "You can't see or modify other applicants' post other than your posted job"
                redirect_to jobs_path
            end
        end
    end


end

app/views/posts/_post_form.html.erb
<div class = "text-center">
   
    <h1>Apply for this post</h1>
    <%= form_with model: [@job, @job.posts.build] do |f|%>
    <div class="form-group row mb-4">
        <%= f.label :name, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :post_description, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_area :post_description, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :username, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :phone_number, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :phone_number, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :city, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :city, class: "form-control" %> 
        </div>
    </div>
    <div class ="col-2 mb-4"> 
        <%= f.label :file %>
        <%= f.file_field :file, class: "form-control-file"%> 
    </div>
    
    <div class="form-group row">
        <div class="col-sm-10 text-center">
        <%= f.submit "Submit", class:"btn btn-primary"%>
        </div>
    </div>
    <%end%>
</div>

app/views/posts/_posts.html.erb
<div class="container post-container">
  <% @posts.each do |post| %>
    <%if post.job == @job && post.is_approved?%>
      <div class="row justify-content-md-center">
          <div class="col-6 mt-6">
            <div class="card shadow mb-5 bg-white rounded post-card">
              <div class="card-header text-center font-weight-bold " id = "post-head">    
                 Posted By <%= link_to post.user.username, user_path(post.user)%>
              </div>
              <div class="card-body">
                <h5 class="card-title text-success text-left text-decoration-none"> <%= post.name%></h5>
                <p class="card-text"><%= truncate(post.post_description, length: 100) %></p>
                <p > <strong>Phone Number:</strong> <%= post.phone_number%></p>
                <p> <strong> City:</strong> <%=post.city%></p>
                <div class="text-center">
                    <%= link_to "View", post_path(post), class: "btn btn-outline-primary"%> 
                </div>
              </div>
              <div class="card-footer text-muted text-center">
                <small> Created <%= time_ago_in_words(post.created_at)%> ago, Edited <%= time_ago_in_words(post.updated_at)%> ago</small>
              </div>
            </div>
          </div>
      </div>
    <%end%>
  <%end%>
</div>

app/views/posts/index.html.erb
<div class="container">
    <h1>Post Requests for this Job</h1>
     <%res = @posts.select {|post| !post.is_approved?}%>
        <%if res.length == 0 %>
            <h3 class = "text-success mt-4 mb-4">No Post request is pending</h3>
        <%end%>
    <% @posts.each do |post| %>
        <%if post.job == @job && !post.is_approved?%>
            <div class="row justify-content-md-center">
                <div class="col-6 mt-6">
                    <div class="card shadow mb-5 bg-white rounded post-card">
                    <div class="card-header text-center font-weight-bold " id = "post-head">    
                        Posted By <%= link_to post.user.username, user_path(post.user)%>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-success text-left text-decoration-none"> <%= post.name%></h5>
                        <p class="card-text"><%= truncate(post.post_description, length: 100) %></p>
                        <p > <strong>Phone Number:</strong> <%= post.phone_number%></p>
                        <p> <strong> City:</strong> <%=post.city%></p>
                        <div class="text-center">
                            <%= link_to "View", post_path(post), class: "btn btn-outline-primary"%> 
                        </div>
                    </div>
                    <div class="card-footer text-muted text-center">
                        <small> Created <%= time_ago_in_words(post.created_at)%> ago, Edited <%= time_ago_in_words(post.updated_at)%> ago</small>
                    </div>
                    </div>
                </div>
            </div>
        <%end%>
    <%end%>
    <h1 class = "mt-4">List of Qualified Candidates for this Job</h1>
    <%= render 'posts'%>
</div>

app/views/posts/my_posts.html.erb
<h1 class = "text-center">See your Job Posts</h1>
<% @my_posts.each do |post|%>
    <div class="container  post-container mt-4">
        <div class="row justify-content-md-center">
            <div class="col-6 mt-6">
                <div class="card border-secondary shadow mb-5 bg-white roundedpost-card">
                <div class="card-header border-secondary text-center font-weight-bold " id = "post-head">    
                    Posted By <%= link_to post.user.username, user_path(post.user)%>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-success text-left text-decoration-none"> <%= post.name%></h5>
                    <p class="card-text"><%= post.post_description %></p>
                    <p> <strong> Phone Number:</strong> <%= post.phone_number%></p>
                    <p> <strong> City:</strong> <%=post.city%></p>
                    <p> <strong> Username:</strong> <%=post.username%></p>
                    <%if post.is_approved?%>
                        <p><strong>Job Status:</strong> Approved</p>
                    <%else%>
                        <p><strong>Job Status:</strong> Pending</p>
                    <%end%>
                    <div class="text-center">
                        <% if post.file.attached?%>
                            <%=button_to post.file.filename, url_for(post.file), method: :get, class: "btn btn-primary"%>
                        <%end%>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <small> Created <%= time_ago_in_words(post.created_at)%> ago, Edited <%= time_ago_in_words(post.updated_at)%> ago</small>
                </div>
                </div>
            </div>
        </div>
    </div>
<%end%>

app/views/posts/new.html.erb
<div class = "text-center mb-4">
    <h1>Apply for this post</h1>
    <%= form_with(model: @post) do |f|%>
    <%= render 'shared/errors', obj: @post%>
    <div class="form-group row mb-4">
        <%= f.label :name, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :post_description, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_area :post_description, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :username, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :phone_number, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :phone_number, class: "form-control" %> 
        </div>
    </div>
    <div class="form-group row mb-4">
        <%= f.label :city, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-8">
        <%= f.text_field :city, class: "form-control" %> 
        </div>
    </div>
    <div class ="col-2 mb-4"> 
        <%= f.label :file %>
        <%= f.file_field :file, class: "form-control-file"%> 
    </div>
    <%= hidden_field_tag(:job_id, @job.id) %>
    <div class="form-group row mb-4">
        <div class="col-sm-10 text-center">
        <%= f.submit "Submit", class:"btn btn-primary"%>
        </div>
    </div>
    <%end%>
</div>

app/views/posts/show.html.erb
<h1 class = "text-center ">Post Show</h1>
<div class="container post-container mt-4">
  <div class="row justify-content-md-center">
      <div class="col-6 mt-6">
        <div class="card shadow mb-5 bg-white rounded post-card">
          <div class="card-header text-center font-weight-bold " id = "post-head">    
              Posted By <%= link_to @post.user.username, user_path(@post.user), class: "text-danger"%>
          </div>
          <div class="card-body">
            <h5 class="card-title text-success text-left text-decoration-none"> <%= @post.name%></h5>
            <p class="card-text"><%= @post.post_description %></p>
            <p > <strong>Phone Number:</strong> <%= @post.phone_number%></p>
            <p> <strong> City:</strong> <%=@post.city%></p>
            <p> <strong> Username:</strong> <%=@post.username%></p>
            <div class="text-center">
              <% if @post.file.attached?%>
                <%=button_to @post.file.filename, url_for(@post.file), method: :get, class: "btn btn-primary"%>
              <%end%>
            </div>
          </div>
          <div class="card-footer text-center text-muted">
            <small> Created <%= time_ago_in_words(@post.created_at)%> ago, Edited <%= time_ago_in_words(@post.updated_at)%> ago</small>
          </div>
        </div>
      </div>
  </div>
</div>

<div class="text-center mb-4">
  <%if !@post.is_approved?%>
    <%= button_to "Accept", respond_to_candidate_path, class: "btn btn-success mb-4"%>
    <%= link_to "Reject", reject_candidate_path(@post), class: "btn btn-danger", data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to delete this post?"}%>  
  <%end%>
</div>